### ISSUE TITLE
What's the current approach for implementing a new WebID?

### ISSUE THREAD

**Issue by tonybranfort** [solid/solid#146]
Is there / what is the current recommended approach for implementing a new WebID?  I'm happy to help update doco if needed if I can be pointed in the right direction.  Looking at: 

#112 Can I use solid/webid right now? (Dec 2016) 
[W3C Wiki Foaf+ssl](https://www.w3.org/wiki/Foaf%2Bssl) (Feb, 2013)
[W3C Wiki WebID](https://www.w3.org/wiki/WebID) (March 2015)
[W3C WebID-TLS spec](https://www.w3.org/2005/Incubator/webid/spec/tls/) (Draft March 2014)

And, I guess I'm looking for confidence that Solid is still solidly behind WebID.  

Newbie to WebID and thought I could quickly set one up with WebID+TLS using my own web server. That hasn't gone as quickly as I was hoping so looking for either confirmation to keep trying with WebID+TLS or try a different implementation approach.  I've also not had luck just creating an ID via another site ( [FoafSites](https://www.w3.org/wiki/FoafSites) like MyOpera or http://my.openlinksw.com/. 

Thanks very much in advance.

**Comment by kidehen** [comment]
@tonybranfort, 

You can get a WebID imprinted to an X.509 Certificate via https://id.myopenlink.net/youid . Just take the option that offers FOAF WebID-Profile doc as your PdP (Profile Data Provider).  Then select "Manual" for Idp (i.e., uploading relations that will be presented to your WebID-Profile doc manually).

**Comment by tonybranfort** [comment]
Great, thanks @kidehen - just what I'm looking for.  This likely isn't the place for support for that but here's what I'm running into.  When I first go to https://id.myopenlink.net/youid/ it immediately asks me to select a certificate - and the only option is an incorrect cert.  So, I cancel to get to the logon.  For both WebID-TLS and TLS options, I get an error for 'No valid X.509 client certificate provided.' without an option to select a cert.   Tried in both Chrome and Firefox.  

![image](https://user-images.githubusercontent.com/16600957/40685708-9b32b2b4-635a-11e8-8766-6c34d2ee996e.png)

**Comment by melvincarvalho** [comment]
Solid is still behind WebID.  This is unlikely to change, because it is what powers the social element.  

Providing a user friendly authentication experience is a moving target, but it is probably our top priority.  Firefox still support the KEYGEN element, TAG guidance is here : 

https://w3ctag.github.io/client-certificates/

There are scripts which create WebIDs too.  Some I've collected.

https://gist.github.com/tomasklapka/ced88b6b72538a5ffe6baffcd898dea8

https://gist.github.com/njh/2432427

https://gist.github.com/njh/2432427/forks

https://github.com/AtomGraph/LinkedDataHub/tree/master/scripts

https://gist.github.com/olberger/7581570/raw

**Comment by kidehen** [comment]
@tonybranfort,

Did you take the option to authenticate using some other protocol, initially? 
If that fails you are more than likely bumping up against an ACL that protects the service. 

Try: http://ods-qa.openlinksw.com/youid .

**Comment by tonybranfort** [comment]
OK, thanks @kidehen - I used http://ods-qa.openlinksw.com/youid to create what they refer to as a "Web-Scale Verifiable Digital Identity Card" after logging in there with my github account.  But lots of questions...

As just a basic/non-developer end user: 
* How do I create a WebID?  When I go to https://dokie.li/, for example, it simply says "Sign in with WebID".   For me, that led to a lot of googling and reading specs and articles of various applicability and currency and then creating my own domain with foaf card and trying to implement my own WebID+TLS.  
* If https://id.myopenlink.net/youid / http://ods-qa.openlinksw.com/youid is the most common/accepted means of creating a WebID right now, a few comments on those sites: 
  * 'WebID' isn't indicated anywhere.  
  * It wasn't clear to me what to do.  I didn't understand that I needed to log into another trusted site (for me Github) to start the process.  I thought I could use a cert that I had created using the WebId-TLS button.  Perhaps silly but that's what I was doing (and what do those do?).  
  * I was concerned about trusting the site.  I don't know these sites and I was uncomfortable granting access to my Github profile - especially as I couldn't find any explanation .  I only went that route after getting feedback here. 
  * What do I do next?  OK, I have a identity URL and p12 packet.  The URL allows me to log into https://dokie.li/ so that's great.  So this is really using WebID and I can feel comfortable that only me and my browser can do that?  
  * How do I integrate the WebID I created with an existing identity / foaf card?  

As a developer: 
* What are the options to implement a WebID?  From a 'simple' end user approach like above integrating into my own domain / web server / foaf card - to ____ ?  
* What actually is happening using https://id.myopenlink.net/youid?  I didn't install the cert that was created by https://id.myopenlink.net/youid but yet I could log into https://dokie.li/ using multiple browsers.  

If these questions aren't helping us to improve WebID for other newbies, ditch 'em.  :)   Just want to say again how much I appreciate the effort and feedback here.  I'm full in on the Solid and WebID objectives.

**Comment by tonybranfort** [comment]
Thanks for the [scripts](https://github.com/solid/solid/issues/146#issuecomment-392948919) @melvincarvalho.  

https://github.com/njh/gen-webid-cert worked for me to create a foaf, pem and p12 files.  I created the foaf on my domain and installed the cert in my browser but that's as far as I've gotten so far. 

These sites you collected now refer to https://github.com/njh/gen-webid-cert : 
* https://gist.github.com/tomasklapka/ced88b6b72538a5ffe6baffcd898dea8
* https://gist.github.com/njh/2432427

**Comment by elf-pavlik** [comment]
> Is there / what is the current recommended approach for implementing a new WebID?

I find [WebID-OIDC](https://github.com/solid/webid-oidc-spec) very promising and I understand new Solid applications will implement it, especially those using https://github.com/solid/solid-auth-client

I think you can try it out on https://solid.community/

I don't know if for sure but possibly one could use self hosted WebID and then just use solid.community service as OIDC issuer https://github.com/solid/webid-oidc-spec#issuer-discovery-from-webid-profile

While WebID-TLS relies on client certificates, WebID-OIDC relies on OpenID Connect (based on OAuth2). This way one doesn't have to deal with various UX issues related to using client certificates in web browsers.

**Comment by kidehen** [comment]
@tonybranfort,

Like many things in life, context is crucial to understanding. My initial responses presumed you simply needed an X.509 cert branded with a WebID. 

If I had assumed the concepts behind WebID and the WebID-TLS protocol were somewhat new I would have directed you to some of posts that include examples etc.., ditto the [YouID homepage](http://youid.openlinksw.com). 

Anyway, I fully agree with making stuff like this "deceptively simple" i.e., simple to use despite underlying infrastructure complexity. 

- [Verifiable Identity that scales to the Web & Internet](https://medium.com/virtuoso-blog/web-logic-sentences-and-the-magic-of-being-you-e2a719d01f73)
- [Simple YouID Exercise](https://medium.com/openlink-software-blog/simple-youid-browser-extension-usage-exercise-57fa3ff6c6b7)

Thanks for the feedback.

**Comment by kidehen** [comment]
@tonybranfort,

I forgot to add links to some demonstrations of dokie.li that I published to YouTube that cover how it works with WebID via our YouID extension etc..

- https://youtu.be/xTPRMol6u4k -- Making static documents live, via annotation 
- https://youtu.be/VZb9wlsbs8g -- Ditto

**Comment by tonybranfort** [comment]
Yeah, definitely context is the struggle here.  I should have started my initial post with "What's the current best, simplest way to create a new WebID that is recommended by Solid?"   

I'm still not sure I have that answer :/.  Again, I say that with all due respect to everyone working on Solid and WebID.  I completely recognize that I might be the guy showing up after you've created the first car and saying "so, yeah, where're the reins??".   So, don't let this be a distraction from real work if it's not helpful to others.  

And maybe the answer to my question is that Solid doesn't want to recommend implementations?

**Comment by kidehen** [comment]
@tonybranfort , 

Fundamentally, a solid-pod will generate a WebID for you following registration, but that doesn't make its usage in regards to authentication protocols obvious. 

By default, you end up with a WebID that isn't immediately usable with the WebID-TLS authentication protocol i.e., it is on immediately usable via the WebID-OIDC authentication protocol. 

Some of the contributions that we are making to the solid-server enable registration with a solid-pod that produce a WebID that is optionally usable with either WebID-OIDC or WebID-TLS (with or without Delegation) as authentication protocols.  The final bit to be added is the X.509 Certificate Generation that automatically handles:

1. WebID placement in Subject Alternative Name (SAN) 
1. Generation of RDF sentences/statements in associated WebID-Profile Doc that connect X.509 Cert and WebID as required by WebID-TLS protocol
1. Additional RDF sentences/statements required in situations where the generated WebID identifies a Delegate of another WebID re WebID-TLS+Delegation protocol

**Comment by RubenVerborgh** [comment]
@tonybranfort Assuming your question has been answered, I'm closing this issue. Feel free to follow up if desired.
